using UnityEngine;

/// <summary>
/// One decoded IMU packet received from the Nicla Vision.
/// </summary>
public struct NiclaImuSample
{
    /// <summary>
    /// Timestamp generated by the Nicla, in milliseconds.
    /// </summary>
    public uint TimestampMilliseconds;

    /// <summary>
    /// Accelerometer output in units of g.
    /// </summary>
    public Vector3 AccelerationG;

    /// <summary>
    /// Gyroscope output in degrees per second.
    /// </summary>
    public Vector3 AngularVelocityDegreesPerSecond;

    /// <summary>
    /// Unity time when the packet was received.
    /// </summary>
    public float UnityReceiveTime;

    /// <summary>
    /// Local packet counter.
    /// </summary>
    public ulong Sequence;

    public bool IsValid;
}